import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";




const CreatePostWizard = () => {
  const {user} = useUser();

  if(!user) return null;

  return (
    <div className="flex gap-3">
      <img src={user.profileImageUrl} alt="Profile image" className="h-14 w-14 rounded-full" />
      <input placeholder="Type some emoji'" className="bg-transparent p-"/>
    </div>
  )
}

const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();
  
  if(isLoading) return <div>...Loading</div>;
  if(!data) return <div>Ooops something went wrong</div>;


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center h-screen">
        <div className="w-full  md:max-w-2xl border-x border-slate-400">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (<div className="flex justify-center"><SignInButton /></div>)}
            {!!user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {data?.map((post) => (
              <div key={post.id} className="border-b border-slate-400 p-8">{post.content}</div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
